# Generated by Django 4.0.6 on 2022-07-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistanceCalculateModel',
        ),
    ]
